version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      test:
        docker:
          - image: circleci/node:12.8.1
        
        steps:
          - checkout
          - run: npm install
          - run: npm test